---
language: node_js
node_js:
  - '12'
cache:
  directories:
    - "node_modules"
services:
    - docker
before_script:
    - npm run build
    - npm install --no-audit
script:
    - npm test
    - npm run prestart
    - docker build -t jamb0t2 .
after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag jamb0t2 $DOCKER_USER/jamb0t2:$TRAVIS_BUILD_NUMBER
    - docker push $DOCKER_USER/jamb0t2:$TRAVIS_BUILD_NUMBER
    - docker tag jamb0t2 $DOCKER_USER/jamb0t2:latest
    - docker push jamb0t2 $DOCKER_USER/jamb0t2:latest
