version: '3.1'

services:
    jamb0t2:
        build:
            context: .
            dockerfile: Dockerfile
        image: chooons/jamb0t2:latest
        container_name: jamb0t2
        env_file: ~/.jamb0t2
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        command: [--auth]
        container_name: mongo
        env_file: ~/.jamb0t2
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DB}
        volumes:
            - ~/mongo.sh:/docker-entrypoint-initdb.d/mongo.sh
            - /data/db:/data/db
        ports:
            - "27017:27107"
