version: '3.1'

services:
    jamb0t2:
        restart: unless-stopped
        volumes:
            - .:/home/node/jamb0t2
            - ./node_modules:/home/node/jamb0t2/node_modules
        command: npm run start:dev
