version: '3'

services:
    jamb0t2:
        build:
            context: .
            dockerfile: Dockerfile
        image: chooons/jamb0t2
        container_name: jamb0t2
        restart: unless-stopped
        env_file: ~/.jamb0t2
        depends_on:
            - mongo
        volumes:
            - .:/home/node/jamb0t2
            - ./node_modules:/home/node/jamb0t2/node_modules
        command: npm run start:dev
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - "27017:27107"
