version: '3'

services:
    jamb0t2:
        image: chooons/jamb0t2:latest
        container_name: jamb0t2
        env_file: ~/.jamb0t2
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        command: [--auth]
        container_name: mongo
        ports:
            - "27017:27107"
